common/models/Signal.php
<?php

namespace common\models;

use Yii;
use \common\models\base\Signal as BaseSignal;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

/**
 * This is the model class for table "signal".
 */
class Signal extends BaseSignal
{

public function behaviors()
    {
        return ArrayHelper::merge(
            parent::behaviors(),
            [
                # custom behaviors
            ]
        );
    }

    public function rules()
    {
        return ArrayHelper::merge(
             parent::rules(),
             [
                  # custom validation rules
             ]
        );
    }

    public static function fromTill($str, $created_at) {
        $year = date('Y', $created_at);
        $month = date('m', $created_at);
        $day = date('d', $created_at);
        preg_match('#([0-9]+):([0-9]+)$#siU', $str, $match);
        $hour = $match[1]*1;

        if ($hour == 0) {
            $hour = 21;
        } else if ($hour == 1) {
            $hour = 22;
        } else if ($hour == 2) {
            $hour = 23;
        } else {
            $hour = $hour - 3;
        }

        if (strlen($hour) == 1) {
            $hour = '0'.$hour;
        }

        $minute = $match[2];
        return strtotime("$year:$month:$day $hour:$minute:00");
    }

    public function getUrl() {
        $category_name = str_replace('/', '', $this->category->name);
        $category_name = strtolower($category_name);

        return Url::to(['signal/view',
            'category_name' => $category_name,
            'year' => date('Y', $this->from),
            'month' => date('m', $this->from),
            'day' => date('d', $this->from),
            'hourminute' => date('H', $this->from) . date('i', $this->from)
        ]);
    }

    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }

    public function getH1()
    {
        $category_name = $this->category->name;
        $weekDay = date('D', $this->from);
        $day = date('d', $this->from);
        $month = date('M', $this->from);
        $year = date('Y', $this->from);
        $time = date('h:i:s', $this->from);
        $amPm = date('A', $this->from);

        return "$category_name Forex ".Yii::t('translate', 'signal')." @ $weekDay $day $month $year $time $amPm UTC";
    }

    public static function monthH1($category_name, $year, $month)
    {
        $category_name = $category_name[0] . $category_name[1] . $category_name[2] . '/' . $category_name[3] . $category_name[4] . $category_name[5];
        $category_name = strtoupper($category_name);
        $date = strtotime("01.$month.$year");

        return "$category_name Forex ".Yii::t('translate', 'signals').", ".date('F', $date)." $year";
    }
}

backend/controllers/SignalController.php
<?php

namespace backend\controllers;


use common\models\Signal;
use common\models\SignalSearch;
use yii\web\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;

/**
* This is the class for controller "SignalController".
*/
class SignalController extends BaseController
{
    public $enableCsrfValidation = false;


    /**
     * Lists all Signal models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel  = new SignalSearch;
        $dataProvider = $searchModel->search($_GET);

        Tabs::clearLocalStorage();

        Url::remember();
        \Yii::$app->session['__crudReturnUrl'] = null;

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    /**
     * Displays a single Signal model.
     * @param integer $id
     *
     * @return mixed
     */
    public function actionView($id)
    {
        \Yii::$app->session['__crudReturnUrl'] = Url::previous();
        Url::remember();
        Tabs::rememberActiveState();

        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Signal model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Signal;

        try {
            if ($model->load($_POST) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } elseif (!\Yii::$app->request->isPost) {
                $model->load($_GET);
            }
        } catch (\Exception $e) {
            $msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
            $model->addError('_exception', $msg);
        }
        return $this->render('create', ['model' => $model]);
    }

    /**
     * Updates an existing Signal model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load($_POST) && $model->save()) {
            return $this->redirect(Url::previous());
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Signal model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        try {
            $this->findModel($id)->delete();
        } catch (\Exception $e) {
            $msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
            \Yii::$app->getSession()->addFlash('error', $msg);
            return $this->redirect(Url::previous());
        }

// TODO: improve detection
        $isPivot = strstr('$id',',');
        if ($isPivot == true) {
            return $this->redirect(Url::previous());
        } elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
            Url::remember(null);
            $url = \Yii::$app->session['__crudReturnUrl'];
            \Yii::$app->session['__crudReturnUrl'] = null;

            return $this->redirect($url);
        } else {
            return $this->redirect(['index']);
        }
    }

    /**
     * Finds the Signal model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Signal the loaded model
     * @throws HttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Signal::findOne($id)) !== null) {
            return $model;
        } else {
            throw new HttpException(404, 'The requested page does not exist.');
        }
    }
}

frontend/controllers/SignalController.php
<?php
namespace frontend\controllers;

use common\models\Category;
use common\models\Signal;
use frontend\models\Locale;
use frontend\models\Visit;
use Yii;
use yii\web\Controller;

/**
 * Site controller
 */
class SignalController extends Controller
{
    public function actionView($category_name, $year, $month, $day, $hourminute)
    {
        $category_name = $category_name[0] . $category_name[1] . $category_name[2] . '/' . $category_name[3] . $category_name[4] . $category_name[5];
        $category_name = strtoupper($category_name);
        $category = Category::findOne(['name' => $category_name]);
        $from = strtotime("$year:$month:$day $hourminute[0]$hourminute[1]:$hourminute[2]$hourminute[3]:00");

        $signal = Signal::find()->where([
            'category_id' => $category->id,
            'from' => $from
        ])->one();

        return $this->render('view', [
            'signal' => $signal,
            'category_name' => $category_name,
            'year' => $year,
            'month' => $month,
            'day' => $day,
            'hourminute' => $hourminute,
        ]);
    }
    
    public function actionMonth($category_name, $year, $month) {
        $startDate = strtotime("$year:$month:01 00:00:00");
        $toDate = strtotime('+1 month', $startDate) - 1;
        $categoryName = strtoupper($category_name);
        $categoryName = preg_replace('#([\w][\w][\w])([\w][\w][\w])#siU', '$1/$2', $categoryName);
        $category = Category::findOne(['name' => $categoryName]);

        $signals = Signal::find()
            ->where("signal.from > $startDate AND signal.from < $toDate")
            ->andWhere(['category_id' => $category->id])
            ->orderBy(['signal.from' => SORT_ASC])
            ->asArray()
            ->all();

        $a_data = array();
        $i = 0;
        foreach($signals as $a_signal)
        {
            if($i == 0)
                $a_data[$i] = $a_signal['profit_pips']*1;
            else
                $a_data[$i] = $a_data[$i-1]+$a_signal['profit_pips'];
            $i++;
        }

        $imageName = "graphic/months/$category_name-$month-$year.png";
        require "pChart/pData.class";
        require "pChart/pChart.class";
        $DataSet = new \pData(); // Создаём объект pData
        $DataSet->AddPoint($a_data, $category->name, "Category"); // Загружаем данные графика 1
        $DataSet->AddAllSeries(); // Добавить все данные для построения
        $Test = new \pChart(1000, 350); // Рисуем графическую плоскость
        $Test->setFontProperties("fonts/tahoma.ttf", 8); // Установка шрифта
        $Test->setGraphArea(50, 40, 950, 300); // Установка области графика
        $Test->drawFilledRoundedRectangle(7, 7, 693, 332, 5, 360, 360, 360); // Выделяем плоскость прямоугольником
        $Test->drawGraphArea(255, 255, 255, true); // Рисуем графическую плоскость
        $Test->drawScale($DataSet->GetData(), $DataSet->GetDataDescription(), SCALE_NORMAL, 0, 0, 0, true, 0, 2); // Рисуем оси и график
        $Test->drawLineGraph($DataSet->GetData(),$DataSet->GetDataDescription()); // Соединяем точки графика линиями
        Yii::$app->formatter->locale = Locale::locale();
        $Test->drawTitle(400, 25, "$categoryName - ".Yii::$app->formatter->asDateTime($startDate, 'php:F Y'), 50, 50, 50, 585); // Выводим заголовок графика
        $Test->drawTitle(-520, 25, Yii::t('translate', 'Profit'), 50, 50, 50, 585);
        $Test->Render($imageName);

        return $this->render('month', [
            'h1' => Signal::monthH1($category_name, $year, $month),
            'signals' => $signals,
            'category_name' => $category_name,
            'year' => $year,
            'month' => $month,
            'imageName' => $imageName
        ]);
    }
}

frontend/controllers/UserController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\web\Controller;

/**
 * Site controller
 */
class UserController extends Controller
{

    public function actions() {
        $this->layout = 'account';
    }

    public function actionAccount()
    {
        if (Yii::$app->user->isGuest) {
            return Yii::$app->response->redirect(['/user-management/auth/login']);
        }
        
        $user = Yii::$app->user->identity;

        if (!empty($_POST)) {
            $_POST['User']['email'] = $_POST['User']['username'];
            $user->load($_POST);
            $user->save();
        }

        return $this->render('account', ['model' => $user]);
    }
    
    public function actionOrder($month)
    {
        if (Yii::$app->user->isGuest) {
            return Yii::$app->response->redirect(['/user-management/auth/login']);
        }

        return $this->render('order');
    }
}

frontend/views/signal/_item.php
<?php
use common\models\Order;
use frontend\models\Visit;
use yii\helpers\Url;

switch($category_name) {
    case 'EUR/USD': {
        $images = '<div class="col-sm-4" style="white-space:nowrap;">
    <img src="/img/eur.jpg" alt="eur">&nbsp;
    <img src="/img/usd.jpg" alt="usd">
</div>';
        break;
    }
    case 'USD/CHF': {
        $images = '<div class="col-sm-4" style="white-space:nowrap;">
    <img src="/img/usd.jpg" alt="usd">&nbsp;
    <img src="/img/chf.jpg" alt="chf">
</div>';
        break;
    }
    case 'GBP/USD': {
        $images = '<div class="col-sm-4" style="white-space:nowrap;">
    <img src="/img/gbp.jpg" alt="gbp">&nbsp;
    <img src="/img/usd.jpg" alt="usd">
</div>';
        break;
    }
    case 'USD/JPY': {
        $images = '<div class="col-sm-4" style="white-space:nowrap;">
    <img src="/img/usd.jpg" alt="usd">&nbsp;
    <img src="/img/jpy.jpg" alt="jpy">
</div>';
        break;
    }
    case 'USD/CAD': {
        $images = '<div class="col-sm-4" style="white-space:nowrap;">
    <img src="/img/usd.jpg" alt="usd">&nbsp;
    <img src="/img/cad.jpg" alt="cad">
</div>';
        break;
    }
    case 'AUD/USD': {
        $images = '<div class="col-sm-4" style="white-space:nowrap;">
    <img src="/img/aud.jpg" alt="aud">&nbsp;
    <img src="/img/usd.jpg" alt="usd">
</div>';
        break;
    }
    case 'EUR/JPY': {
        $images = '<div class="col-sm-4" style="white-space:nowrap;">
    <img src="/img/eur.jpg" alt="eur">&nbsp;
    <img src="/img/jpy.jpg" alt="jpy">
</div>';
        break;
    }
    case 'NZD/USD': {
        $images = '<div class="col-sm-4" style="white-space:nowrap;">
    <img src="/img/nzd.jpg" alt="nzd">&nbsp;
    <img src="/img/usd.jpg" alt="usd">
</div>';
        break;
    }
    case 'GBP/CHF': {
        $images = '<div class="col-sm-4" style="white-space:nowrap;">
    <img src="/img/gbp.jpg" alt="gbp">&nbsp;
    <img src="/img/chf.jpg" alt="chf">
</div>';
        break;
    }
}

$profitPips = str_replace('+', '', $signal->profit_pips);

$profitPips = '
<div class="col-sm-4 signal-value profit-color">
'.(($profitPips[0] == '-') ? $profitPips : "+".$profitPips).'
</div>';

$features = '';
$class = '';
$ss = '';

if($signal->condition == 'Filled') {
    $class = 'filled';
    $ss = 'Filled';
    if ($signal->state == 'Buy') {
        $features = '
                    <div class="signal-item">
						<div class="row">
							<div class="col-sm-8">'.Yii::t("translate", "boughtAt").'</div>
							<div class="col-sm-4 signal-value signal-color signal-price">'.$signal->byu_at.'</div>
						</div>
					</div>
					<div class="signal-item">
						<div class="row">
							<div class="col-sm-8">'.Yii::t("translate", "soldAt").'</div>
							<div class="col-sm-4 signal-value signal-color signal-price">'.$signal->sell_at.'</div>
						</div>
					</div>
					<div class="signal-item">
						<div class="row">
							<div class="col-sm-8">'.Yii::t("translate", "profitPips").'</div>
							'.$profitPips.'
						</div>
					</div>
        ';
    } else if ($signal->state == 'Sell') {
        $features = '
					<div class="signal-item">
						<div class="row">
							<div class="col-sm-8">'.Yii::t("translate", "soldAt").'</div>
							<div class="col-sm-4 signal-value signal-color signal-price">'.$signal->sell_at.'</div>
						</div>
					</div>
                    <div class="signal-item">
						<div class="row">
							<div class="col-sm-8">'.Yii::t("translate", "boughtAt").'</div>
							<div class="col-sm-4 signal-value signal-color signal-price">'.$signal->byu_at.'</div>
						</div>
					</div>
					<div class="signal-item">
						<div class="row">
							<div class="col-sm-8">'.Yii::t("translate", "profitPips").'</div>
							'.$profitPips.'
						</div>
					</div>
        ';
    }

} else if($signal->condition == 'Cancelled') {
    $class = 'cancelled';
    $ss = 'Cancelled';
    if ($signal->state == 'Buy') {
		 $features = '
                    <div class="signal-item">
						<div class="row">
							<div class="col-sm-8">'.Yii::t("translate", "boughtAt").'</div>
							<div class="col-sm-4 signal-value signal-color signal-price">'.$signal->byu_at.'</div>
						</div>
					</div>
					<div class="signal-item">
						<div class="row">
							<div class="col-sm-8">'.Yii::t("translate", "takeProfitAt").'</div>
							<div class="col-sm-4 signal-value signal-color signal-price">'.$signal->take_profit_at.'</div>
						</div>
					</div>
					<div class="signal-item">
						<div class="row">
							<div class="col-sm-8">'.Yii::t("translate", "stopLossAt").'</div>
							<div class="col-sm-4 signal-value signal-color signal-price">'.$signal->stop_loss_at.'</div>
						</div>
					</div>
        ';
    } else if ($signal->state == 'Sell') {
		 $features = '
               <div class="signal-item">
						<div class="row">
							<div class="col-sm-8">'.Yii::t("translate", "soldAt").'</div>
							<div class="col-sm-4 signal-value signal-color signal-price">'.$signal->sell_at.'</div>
						</div>
					</div>
					<div class="signal-item">
						<div class="row">
							<div class="col-sm-8">'.Yii::t("translate", "takeProfitAt").'</div>
							<div class="col-sm-4 signal-value signal-color signal-price">'.$signal->take_profit_at.'</div>
						</div>
					</div>
					<div class="signal-item">
						<div class="row">
							<div class="col-sm-8">'.Yii::t("translate", "stopLossAt").'</div>
							<div class="col-sm-4 signal-value signal-color signal-price">'.$signal->stop_loss_at.'</div>
						</div>
					</div>
        ';
    }
} else {
    switch($signal->state) {
        case 'Buy': {
            $class = 'buy';
            $ss = 'Buy';
            $features = '
                    <div class="signal-item">
						<div class="row">
							<div class="col-sm-8">'.Yii::t("translate", "buyAt").'</div>
							<div class="col-sm-4 signal-value signal-color signal-price">'.$signal->byu_at.'</div>
						</div>
					</div>
					<div class="signal-item">
						<div class="row">
							<div class="col-sm-8">'.Yii::t("translate", "takeProfitAt").'</div>
							<div class="col-sm-4 signal-value signal-color signal-price">'.$signal->take_profit_at.'</div>
						</div>
					</div>
					<div class="signal-item">
						<div class="row">
							<div class="col-sm-8">'.Yii::t("translate", "stopLossAt").'</div>
							<div class="col-sm-4 signal-value signal-color signal-price">'.$signal->stop_loss_at.'</div>
						</div>
					</div>
        ';
            break;
        }
        case 'Sell': {
            $class = 'sell';
            $ss = 'Sell';
            $features = '
                    <div class="signal-item">
						<div class="row">
							<div class="col-sm-8">'.Yii::t("translate", "sellAt").'</div>
							<div class="col-sm-4 signal-value signal-color signal-price">'.$signal->sell_at.'</div>
						</div>
					</div>
					<div class="signal-item">
						<div class="row">
							<div class="col-sm-8">'.Yii::t("translate", "takeProfitAt").'</div>
							<div class="col-sm-4 signal-value signal-color signal-price">'.$signal->take_profit_at.'</div>
						</div>
					</div>
					<div class="signal-item">
						<div class="row">
							<div class="col-sm-8">'.Yii::t("translate", "stopLossAt").'</div>
							<div class="col-sm-4 signal-value signal-color signal-price">'.$signal->stop_loss_at.'</div>
						</div>
					</div>
        ';
            break;
        }
    }
}

$timeLeft = '';
$timeDiff = time() - $signal->from;
if ($timeDiff < 86400) {
    $hours = intval($timeDiff / 3600);
    $minutes = intval($timeDiff / 3600);
}

$gmt = date('P', $signal->from);
$sign = $gmt[0];
$digit = ($gmt[1] . $gmt[2]) * 1;
$po = $sign . $digit . ' hours';

$from = strtotime($po, $signal->from);
$till = strtotime($po, $signal->till);

?>
<div class="col-xs-4 signal-cell">
    <div class="signal-border <?=(!$active && !Order::isActive())? "delay" : $class?>">
        <div class="signal_border_size">
            <div class="signal-header">
                <div class="row">
                    <?=$images?>
                    <div class="col-sm-8">
                        <a href="<?=$signal->url?>" style="text-decoration:none;" title="Free <?=$category_name?> Forex signal"><?=$category_name?></a>
                    </div>
                </div>
            </div>
            <?php if ($active || Order::isActive()) { ?>
                <div class="signal-body">
                    <div class="signal-item signal-ago1">
                        <div class="row">
                            <div class="col-sm-6"><?=$category_name?> <?=Yii::t('translate', 'signal')?></div>
                            <div class="col-sm-6 signal-color text-right">
                                <small><?=$timeLeft?></small>
                            </div>
                        </div>
                    </div>
                    <div class="signal-item">
                        <div class="row">
                            <div class="col-sm-4"><?=Yii::t('translate', 'from')?></div>
                            <div class="col-sm-8 signal-value signal-color">
                                <span class="gmt">GMT<?=date('P', $signal->from)?></span>
                                <?=date('H:i', $from);?>
                            </div>
                        </div>
                    </div>
                    <div class="signal-item">
                        <div class="row">
                            <div class="col-sm-4"><?=Yii::t('translate', 'till')?></div>
                            <div class="col-sm-8 signal-value signal-color">
                                <span class="gmt">GMT<?=date('P', $signal->till)?></span>
                                <?=date('H:i', $till);?>
                            </div>
                        </div>
                    </div>
                    <div class="signal-item signal-status signal-color text-center"><?=Yii::t('translate', strtolower($ss))?></div>
                    <?=$features?>
                    <?php if (!Order::isActive()) { ?>
                        <div class="signal-item">
                            <div class="row">
                                <div class="col-sm-8">
                                    <a href="<?=Url::to(['/user/account'])?>"><?=Yii::t('translate', 'Subscribe to signals')?> <?=$signal->category->name?></a>
                                </div>
                                <div class="col-sm-4  signal-value signal-color">
                                    <a href="<?=Url::to(['/user/account'])?>" title="<?=Yii::t('translate', 'Subscribe to signals')?> <?=$signal->category->name?>">
                                        <img alt="" style="border:0;margin-bottom:0;" src="https://forexcdn.appspot.com/fx3/img/signal/mail_sell.png">
                                        <img alt="" style="border:0;margin-bottom:0;" src="https://forexcdn.appspot.com/fx3/img/signal/mail_sell.png">
                                        <img alt="" style="border:0;margin-bottom:0;" src="https://forexcdn.appspot.com/fx3/img/signal/mail_sell.png">
                                    </a>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            <?php } else { ?>
                <div class="signal-body">
                    <div style="text-align:center;">
                        <div style="margin-top:0.5em;margin-bottom:0.5em;">
                            <img alt="" src="/img/bell72.png">
                        </div>
                        <div style="font-weight:bold;"><?=$category_name?> <?=Yii::t('translate', 'signal')?></div>
                        <div style="margin-top:0.5em;">
                            <a href="<?=Url::to(['/user-management/auth/login'])?>"><?=Yii::t('translate', 'Login')?></a>
                            &nbsp;
                            <a href="<?=Url::to(['/user-management/auth/registration'])?>"><?=Yii::t('translate', 'Register')?></a>
                        </div>
                        <div style="margin-top:1em;" class="alert alert-success">
                            <div>
                                <a class="alert-success" href="<?=Url::to(['/user/account'])?>">
                                    <?=Yii::t('translate', 'subscribe')?>
                                </a>
                            </div>
                            <div>
                                <em><?=Yii::t('translate', 'subscribeText')?></em>
                            </div>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
</div>

frontend/views/signal/month.php
<?php
use common\models\Signal;
use frontend\models\Locale;

$cn = str_replace('/', '', strtolower($category_name));

$this->params['category_name'] = $cn;
$this->params['year'] = $year;
$this->params['month'] = $month;
$summ = 0;
Yii::$app->formatter->locale = Locale::locale();
$M = Yii::$app->formatter->asDateTime(strtotime("01.$month.$year"), 'php:M')
?>
<div class="row">
    <h1><?=$h1?></h1>
</div>
<div class="row">
    <div id="month_graph">
        <img src="/<?=$imageName?>">
        <div class="month_graph_inner">
            <span class="first">3 <?=$M?></span>
            <span>10 <?=$M?></span>
            <span>17 <?=$M?></span>
            <span class="last">24 <?=$M?></span>
        </div>
    </div>
</div>
<div class="table-responsive">
    <table class="st table table-hover">
        <tr>
            <th class="sh" style="text-align:center;"><?=Yii::t('translate', 'Date, time')?></th>
            <th class="sh" style="text-align:center;"><?=Yii::t('translate', 'Order')?></th>
            <th class="sh" style="text-align:center;"><?=Yii::t('translate', 'Take Profit')?></th>
            <th class="sh" style="text-align:center;"><?=Yii::t('translate', 'Stop Loss')?></th>
            <th class="sh" style="text-align:center;"><?=Yii::t('translate', 'State')?></th>
            <th class="sh" style="text-align:center;"><?=Yii::t('translate', 'Entry')?></th>
            <th class="sh" style="text-align:center;"><?=Yii::t('translate', 'Exit')?></th>
            <th class="sh" style="text-align:center;"><?=Yii::t('translate', 'Profit')?></th>
        </tr>
        <?php foreach($signals as $signal) {
            $dateTime = Yii::$app->formatter->asDateTime($signal['from'], 'php:D d M Y h:i:s A');
            $summ += $signal['profit_pips']*1;

            $class = '';
            if ($signal['condition'] == 'Cancelled') {
                $class = 'cancelled';
            } else {
                if ($signal['profit_pips']*1 > 0) {
                   $class = 'filled-profit';
                } else if ($signal['profit_pips']*1 < 0) {
                    $class = 'filled-loss';
                }
            }

            echo '
                <tr class="'.$class.'">
                    <td class="sd" style="text-align:center;">
                                <span>
                                    <small>
                                        <a style="" href="'.Signal::findOne($signal['id'])->url.'">
                                            							'.$dateTime.' UTC
                                        </a>
                                    </small>
                                </span>
                    </td>
                    <td class="sd" style="text-align:center;">'.Yii::t('translate', strtolower($signal['state'])).'</td>
                    <td class="sd" style="text-align:center;">'.$signal['take_profit_at'].'</td>
                    <td class="sd" style="text-align:center;">'.$signal['stop_loss_at'].'</td>
                    <td class="sd" style="text-align:center;;word-wrap: break-word;">'.Yii::t('translate', strtolower($signal['condition'])).'</td>';
            if ($signal['state'] == 'Buy') {
                echo '<td class="sd" style="text-align:center;">'.$signal['byu_at'].'</td>
                        <td class="sd" style="text-align:center;">'.$signal['sell_at'].'</td>';
            } else {
                echo '<td class="sd" style="text-align:center;">'.$signal['sell_at'].'</td>
                    <td class="sd" style="text-align:center;">'.$signal['byu_at'].'</td>';
            }

            echo '<td class="sd" style="text-align:center;">'.$signal['profit_pips'].'</td>
                </tr>';
        }

        echo '<tr class="filled-profit">
                    <td colspan="7" class="sd" style="text-align:left;padding-left:53px;">
                         <span style="font-weight:bold;">'.Yii::t('translate', 'Total').'</span>
                    </td>
                    <td class="sdplus" style="text-align:center;font-weight:bold;">'.$summ.'</td>
                </tr>';
        ?>
    </table>
</div>

frontend/views/signal/view.php
<?php
$cn = str_replace('/', '', strtolower($category_name));

$this->params['category_name'] = $cn;
$this->params['year'] = $year;
$this->params['month'] = $month;
$this->params['day'] = $day;
$this->params['hourminute'] = $hourminute;

?>
<div class="row">
    <h1><?=$signal->h1?></h1>
</div>
<br>
<br>
<div class="row">
    <div class="col-sm-4"></div>
    <?=$this->render('_item', [
        'signal' => $signal,
        'category_name' => $category_name
    ])?>
    <div class="col-sm-4"></div>
</div>
<br>
<br>
<br>
<div class="row">
    <h1><?=Yii::t('translate', 'instructions')?></h1>
</div>

<div class="text-regular"><?=Yii::t('translate', 'instructionsText1')?></div>
<div class="text-regular"><?=Yii::t('translate', 'instructionsText2')?></div>